// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RetroGameStore.Models;

#nullable disable

namespace RetroGameStore.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260603074404_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("RetroGameStore.Models.Game", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CoverImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<int>("Genre")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LowStockThreshold")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Platform")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<int>("ReleaseYear")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Stock")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Games");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CoverImageUrl = "/images/games/crash_bandicoot.png",
                            Genre = 6,
                            LowStockThreshold = 3,
                            Platform = 0,
                            Price = 29.99m,
                            ReleaseYear = 1996,
                            Stock = 5,
                            Title = "Crash Bandicoot"
                        },
                        new
                        {
                            Id = 2,
                            CoverImageUrl = "/images/games/gran_turismo_3.png",
                            Genre = 4,
                            LowStockThreshold = 3,
                            Platform = 1,
                            Price = 24.99m,
                            ReleaseYear = 2001,
                            Stock = 2,
                            Title = "Gran Turismo 3"
                        },
                        new
                        {
                            Id = 3,
                            CoverImageUrl = "/images/games/pokemon_red.png",
                            Genre = 2,
                            LowStockThreshold = 3,
                            Platform = 2,
                            Price = 34.99m,
                            ReleaseYear = 1996,
                            Stock = 8,
                            Title = "Pokémon Red"
                        },
                        new
                        {
                            Id = 4,
                            CoverImageUrl = "/images/games/zelda_minish_cap.png",
                            Genre = 1,
                            LowStockThreshold = 3,
                            Platform = 3,
                            Price = 39.99m,
                            ReleaseYear = 2004,
                            Stock = 3,
                            Title = "The Legend of Zelda: Minish Cap"
                        },
                        new
                        {
                            Id = 5,
                            CoverImageUrl = "/images/games/super_mario_64.png",
                            Genre = 6,
                            LowStockThreshold = 3,
                            Platform = 4,
                            Price = 44.99m,
                            ReleaseYear = 1996,
                            Stock = 1,
                            Title = "Super Mario 64"
                        },
                        new
                        {
                            Id = 6,
                            CoverImageUrl = "/images/games/zelda_ocarina.png",
                            Genre = 1,
                            LowStockThreshold = 3,
                            Platform = 4,
                            Price = 49.99m,
                            ReleaseYear = 1998,
                            Stock = 2,
                            Title = "The Legend of Zelda: Ocarina of Time"
                        },
                        new
                        {
                            Id = 7,
                            CoverImageUrl = "/images/games/smash_bros_melee.png",
                            Genre = 5,
                            LowStockThreshold = 3,
                            Platform = 5,
                            Price = 54.99m,
                            ReleaseYear = 2001,
                            Stock = 4,
                            Title = "Super Smash Bros. Melee"
                        },
                        new
                        {
                            Id = 8,
                            CoverImageUrl = "/images/games/resident_evil.png",
                            Genre = 0,
                            LowStockThreshold = 3,
                            Platform = 0,
                            Price = 19.99m,
                            ReleaseYear = 1996,
                            Stock = 6,
                            Title = "Resident Evil"
                        });
                });

            modelBuilder.Entity("RetroGameStore.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("GameId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("RetroGameStore.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "admin@retrogames.com",
                            FullName = "Admin User",
                            Password = "admin123",
                            Role = 0
                        },
                        new
                        {
                            Id = 2,
                            Email = "staff@retrogames.com",
                            FullName = "Staff Member",
                            Password = "staff123",
                            Role = 1
                        },
                        new
                        {
                            Id = 3,
                            Email = "customer@retrogames.com",
                            FullName = "John Customer",
                            Password = "customer123",
                            Role = 2
                        });
                });

            modelBuilder.Entity("RetroGameStore.Models.Order", b =>
                {
                    b.HasOne("RetroGameStore.Models.Game", "Game")
                        .WithMany("Orders")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RetroGameStore.Models.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("User");
                });

            modelBuilder.Entity("RetroGameStore.Models.Game", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("RetroGameStore.Models.User", b =>
                {
                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
