// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RetroGameStore.Models;

#nullable disable

namespace RetroGameStore.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("RetroGameStore.Models.Game", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CoverImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<int>("Genre")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LowStockThreshold")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Platform")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<int>("ReleaseYear")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Stock")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Games");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CoverImageUrl = "/images/games/crash_bandicoot.png",
                            Genre = 6,
                            LowStockThreshold = 3,
                            Platform = 0,
                            Price = 29.99m,
                            ReleaseYear = 1996,
                            Stock = 5,
                            Title = "Crash Bandicoot"
                        },
                        new
                        {
                            Id = 2,
                            CoverImageUrl = "/images/games/gran_turismo_3.png",
                            Genre = 4,
                            LowStockThreshold = 3,
                            Platform = 1,
                            Price = 24.99m,
                            ReleaseYear = 2001,
                            Stock = 2,
                            Title = "Gran Turismo 3"
                        },
                        new
                        {
                            Id = 3,
                            CoverImageUrl = "/images/games/pokemon_red.png",
                            Genre = 2,
                            LowStockThreshold = 3,
                            Platform = 2,
                            Price = 34.99m,
                            ReleaseYear = 1996,
                            Stock = 8,
                            Title = "Pokémon Red"
                        },
                        new
                        {
                            Id = 4,
                            CoverImageUrl = "/images/games/zelda_minish_cap.png",
                            Genre = 1,
                            LowStockThreshold = 3,
                            Platform = 3,
                            Price = 39.99m,
                            ReleaseYear = 2004,
                            Stock = 3,
                            Title = "The Legend of Zelda: Minish Cap"
                        },
                        new
                        {
                            Id = 5,
                            CoverImageUrl = "/images/games/super_mario_64.png",
                            Genre = 6,
                            LowStockThreshold = 3,
                            Platform = 4,
                            Price = 44.99m,
                            ReleaseYear = 1996,
                            Stock = 1,
                            Title = "Super Mario 64"
                        },
                        new
                        {
                            Id = 6,
                            CoverImageUrl = "/images/games/zelda_ocarina.png",
                            Genre = 1,
                            LowStockThreshold = 3,
                            Platform = 4,
                            Price = 49.99m,
                            ReleaseYear = 1998,
                            Stock = 2,
                            Title = "The Legend of Zelda: Ocarina of Time"
                        },
                        new
                        {
                            Id = 7,
                            CoverImageUrl = "/images/games/smash_bros_melee.png",
                            Genre = 5,
                            LowStockThreshold = 3,
                            Platform = 5,
                            Price = 54.99m,
                            ReleaseYear = 2001,
                            Stock = 4,
                            Title = "Super Smash Bros. Melee"
                        },
                        new
                        {
                            Id = 8,
                            CoverImageUrl = "/images/games/resident_evil.png",
                            Genre = 0,
                            LowStockThreshold = 3,
                            Platform = 0,
                            Price = 19.99m,
                            ReleaseYear = 1996,
                            Stock = 6,
                            Title = "Resident Evil"
                        });
                });

            modelBuilder.Entity("RetroGameStore.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("GameId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DeliveryAddress")
                        .HasColumnType("TEXT");

                    b.Property<string>("FulfillmentType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            Id = 101,
                            FulfillmentType = "Store Pickup",
                            GameId = 1,
                            OrderDate = new DateTime(2026, 6, 1, 10, 30, 0),
                            PaymentMethod = "Cash",
                            Quantity = 1,
                            Status = 0,
                            TotalPrice = 29.99m,
                            UserId = 3
                        },
                        new
                        {
                            Id = 102,
                            DeliveryAddress = "Demo Street 12",
                            FulfillmentType = "Delivery to Home",
                            GameId = 3,
                            OrderDate = new DateTime(2026, 6, 1, 12, 10, 0),
                            PaymentMethod = "Cash",
                            Quantity = 2,
                            Status = 2,
                            TotalPrice = 69.98m,
                            UserId = 3
                        },
                        new
                        {
                            Id = 103,
                            FulfillmentType = "Store Pickup",
                            GameId = 7,
                            OrderDate = new DateTime(2026, 6, 2, 15, 45, 0),
                            PaymentMethod = "Cash",
                            Quantity = 1,
                            Status = 0,
                            TotalPrice = 54.99m,
                            UserId = 4
                        },
                        new
                        {
                            Id = 104,
                            DeliveryAddress = "Demo Avenue 7",
                            FulfillmentType = "Delivery to Home",
                            GameId = 8,
                            OrderDate = new DateTime(2026, 6, 3, 9, 20, 0),
                            PaymentMethod = "Cash",
                            Quantity = 1,
                            Status = 0,
                            TotalPrice = 19.99m,
                            UserId = 5
                        });
                });

            modelBuilder.Entity("RetroGameStore.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "admin@rgsdemo.com",
                            FullName = "Nora Admin",
                            Password = "Admin@123",
                            Role = 0
                        },
                        new
                        {
                            Id = 2,
                            Email = "staff@rgsdemo.com",
                            FullName = "Omar Inventory",
                            Password = "Staff@123",
                            Role = 1
                        },
                        new
                        {
                            Id = 3,
                            Email = "lina@rgsdemo.com",
                            FullName = "Lina Carter",
                            Password = "Demo@123",
                            Role = 2
                        },
                        new
                        {
                            Id = 4,
                            Email = "maya@rgsdemo.com",
                            FullName = "Maya Collins",
                            Password = "Demo@123",
                            Role = 2
                        },
                        new
                        {
                            Id = 5,
                            Email = "adam@rgsdemo.com",
                            FullName = "Adam Brooks",
                            Password = "Demo@123",
                            Role = 2
                        });
                });

            modelBuilder.Entity("RetroGameStore.Models.Order", b =>
                {
                    b.HasOne("RetroGameStore.Models.Game", "Game")
                        .WithMany("Orders")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RetroGameStore.Models.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("User");
                });

            modelBuilder.Entity("RetroGameStore.Models.Game", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("RetroGameStore.Models.User", b =>
                {
                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
